### ISSUE TITLE
Move controversial instances to `Data.String.Conversions.Unsafe`?

### ISSUE THREAD

**Issue by fisx** [soenkehahn/string-conversions#13]
translating bytestrings to text is not always well-defined, and there is no single best answer to what it means if a byte sequence is not defined as a character in UTF8.  the choices this library makes are great in general, but i would like to be able to opt out of them.

this would require `-Wno-orphans` in the unsafe module, but i'm ok with that.

would you accept a PR for this?

(also, hi :-)

**Comment by soenkehahn** [comment]
Hi. :)

I'm not 100% sure but I think this wouldn't work well in practice, because of how instances are imported (or scoped) in Haskell. So if any of your transitive dependencies imports the `Unsafe` module, you'll get all the unsafe instances without importing them yourself. I think.

There could be a separate type-class for safe conversions though.

Apart from that I think that I would prefer to keep the existing behavior of `Data.String.Conversions`. I'm not completely against adding a `Data.String.Conversions.Safe` module that only exposes safe conversions however.

To be honest, I'm not fully convinced yet that this change is worthwhile though. Do you have a concrete example of a project where you do have `ByteString`s that you are tempted to convert to either `String` or `Text` using `cs`, but where you would opt for a safer api? Or some other concrete example that motivates this change from your perspective?

**Comment by fisx** [comment]
No concrete use case, I just think that if there can be an error, that should be obvious from the types.  If you want to make a case for using a library in security-sensitive code, it's nice if you don't have to admit that it sometimes it eats bytes from your strings when you clearly don't want it to.

You are right though, my idea was wrong.  I like the extra type class.  I'll think about it some more.

**Comment by fisx** [comment]
yeah, not worth it.  (-:

it might improve the library marginally, but i decided to not spend any more time on the idea.

thanks for the helpful feedback!
